apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-service
    app.kubernetes.io/instance: api-service
    app.kubernetes.io/name: api-service
  name: api-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: api-service
    app.kubernetes.io/name: api-service
  sessionAffinity: None
  type: ClusterIP
